theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
title: Shalmali's homepage
full_name: Shalmali Walimbe
email: swalimbe@iu.edu
baseurl: ""
url: "shal96.github.io"
description: Digital pages that document my professional and personal life.

show_excerpts: true 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

minima:
  social_links:
    github: Shal96
    linkedin: shalmaliwalimbe
